TRAIN_FACE_ROOT = "./feats/facenetfeats/v1/faces"
TRAIN_AUDIO_ROOT = "./feats/ecappafeats/v1/voices"
TEST_FEATURE_ROOT = "./features/test"
DEBUG_DIR = "./csv_files/submission/debug"


FIRST_PASS_MIN_SCORE_STRONG = 10.0
FIRST_PASS_MIN_SCORE_WEAK = 2.0

RUN_SHARED_CONSISTENCY_REFINEMENT = True
SHARED_CLUSTER_THRESHOLD = 0.24
SHARED_MIN_FACE_GAP = 0.04
SHARED_MIN_VIDEO_GAP = 0.04
SHARED_MIN_COMBINED_SCORE = 9.0
SHARED_AUDIO_BLOCK_GAP = 0.06
SHARED_MAX_REFINEMENTS = 2

RUN_LONG_TRACK_VIDEO_REFINEMENT = True
LONG_TRACK_TOPK_VIDEO = 50
LONG_TRACK_MAX_CONFIDENCE = 0.40
LONG_TRACK_MAX_FACE_RANK = 15
LONG_TRACK_MIN_VIDEO_VOTES = 2
LONG_TRACK_MIN_TOTAL_FRAMES = 60
LONG_TRACK_MIN_FRAMES_PER_VOTE = 30
LONG_TRACK_MIN_VIDEO_SCORE = 0.29
LONG_TRACK_MIN_AUDIO_RANK = 10
LONG_TRACK_MAX_REFINEMENTS = 1

GROUP_CLUSTER_THRESHOLD = 0.30
GROUP_MIN_CLUSTER_SIZE = 1
GROUP_MIN_MAJORITY_RATIO = 0.80
GROUP_SEEN_MIN_RATIO = 0.75
GROUP_SEEN_MIN_SIZE = 3
GROUP_MAX_CHANGES_SEEN = 2
GROUP_MAX_CHANGES_UNSEEN = 2